# Docker Compose mínimo para Sistema de Gestión de Inventario
# ¡Levanta en 1 comando: docker-compose up!

version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Volumen persistente para la base de datos
      - ./instance:/app/instance
      # Volumen para logs
      - ./logs:/app/logs
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DEBUG=true
      - DATABASE_URL=sqlite:///instance/stock_management.db
      - SECRET_KEY=dev-secret-key-change-in-production
      - JWT_SECRET_KEY=dev-jwt-secret-change-in-production
    restart: unless-stopped

volumes:
  # Los volúmenes se mapean directamente a directorios locales
